version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz_app
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_NAME= "Quiz_Management_System"
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:pfeiVmWXldkjSlTBkCmqDTsp34yN2dhyxwsOtDUb9Po=
      - APP_URL= "http://quiz.test"
      - CENTRAL_DOMAIN= "quiz.test"
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=quiz_management
      - DB_USERNAME=root
      - DB_PASSWORD=

  db:
    image: mysql:8.0
    container_name: quiz_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: quiz_management
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
